version: "3.7"
services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.0
    ports:
      - "2379"
      - "2380"
    networks:
      - ects
  mysql:
    image: mysql
    ports:
      - 3306
    networks:
      - ects
  ects:
    image: betterde/ects:latest
networks:
  ects:
volumes:
  data: