version: "3.7"
services:
  etcd_dev:
    image: gcr.io/etcd-development/etcd:v3.3.12
    hostname: etcd_dev
    container_name: etcd_dev
    networks:
      - ects
  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ects
    networks:
      - ects
  ects:
    image: ects:0.5.1
    hostname: ects
    container_name: ects
    command: ects init -m web
    ports:
      - 9701:9701
    depends_on:
      - mysql
      - etcd_dev
    networks:
      - ects
networks:
  ects:
    name: ects